// GENERATED by tools/cad/extract_geometry.py from CAD/FullASSY.step. Do not edit by hand.
// All lengths in millimetres, angles in degrees, in the CAD frame (z up, origin at the
// centre of the plate's bottom face in the CAD pose). Values are the mean over the three
// legs; the max-min spread across legs is noted where it is non-zero.
#pragma once

namespace bbp::cad {

// Azimuths of the three spherical joints (sorted).
inline constexpr double kLegAzimuthDeg[3] = {-150.000000, -30.000000, 90.000000};
inline constexpr double kPivotRadius = 44.006737;   // spread 7.96e-13
inline constexpr double kPivotZ = -90.934034;
inline constexpr double kCrankLength = 50.000000;   // spread 1.42e-14
inline constexpr double kCrankAngleInCadDeg = -45.004386;  // crank angle above horizontal in the CAD pose
inline constexpr double kRodLength = 118.598312;     // spread 9.66e-13
inline constexpr double kJointRadius = 94.000000;
inline constexpr double kJointZ = -8.598312;
// Perpendicular distance of each leg plane from the central axis (ideal design: 0).
inline constexpr double kLegPlaneOffset = -0.770000;

inline constexpr double kPlateTopZ = 5.000000;
inline constexpr double kPlateBottomZ = 0.000000;
inline constexpr double kPlateRadius = 100.000000;
inline constexpr double kPlateVolume = 158016.211922;     // mm^3
inline constexpr double kPlateComZ = 2.472000;
// Plate second moments about its centre of mass per unit density (mm^5).
inline constexpr double kPlateIxxPerDensity = 3.971920e+08;
inline constexpr double kPlateIyyPerDensity = 3.971920e+08;
inline constexpr double kPlateIzzPerDensity = 7.936848e+08;

inline constexpr double kCrankVolume = 3736.053944;     // mm^3
// Crank centre of mass relative to the pivot in the CAD pose (radial u, vertical v).
inline constexpr double kCrankComU = 16.269781;
inline constexpr double kCrankComV = -5.456425;
inline constexpr double kCrankIPivotPerDensity = 2.612351e+06;  // mm^5, about the pivot axis
inline constexpr double kRodVolume = 8541.304501;       // mm^3

inline constexpr double kBallRadius = 10.000000;
inline constexpr double kBallCentreZ = 15.000000;

// Camera (OV2710 module): top of the lens element and the module body extent.
inline constexpr double kCameraLensTopZ = -90.404034;
inline constexpr double kCameraLensBottomZ = -92.404035;
inline constexpr double kCameraBodyBottomZ = -118.404034;
inline constexpr double kCameraX = -0.000000;
inline constexpr double kCameraY = -0.000000;

}  // namespace bbp::cad
