"""Extract the platform geometry from CAD/FullASSY.step and generate
core/include/bbp/core/cad_geometry.hpp.

Run with FreeCAD's bundled interpreter (the STEP import needs FreeCAD/OCCT):

    "C:/Program Files/FreeCAD 1.0/bin/freecadcmd.exe" -c "exec(open('tools/cad/extract_geometry.py').read())"

from the repository root. The script identifies features by their CAD part
names and characteristic surfaces (crank hub radius 10.75 mm, pin hole
radius 2.0 mm, 8 mm joint balls), so it must be revisited if those change.
"""
import math
import os

import FreeCAD as App
import Import

ROOT = os.getcwd()
STEP = os.path.join(ROOT, "CAD", "FullASSY.step")
OUT = os.path.join(ROOT, "core", "include", "bbp", "core", "cad_geometry.hpp")

doc = App.newDocument("bbp_extract")
Import.insert(STEP, doc.Name)


def gshape(o):
    sh = o.Shape.copy()
    sh.Placement = o.getGlobalPlacement()
    return sh


def parts(prefix):
    return [o for o in doc.Objects if o.TypeId == "Part::Feature" and o.Label.startswith(prefix)]


def cylinders(sh, radius, tol=0.02):
    return [(f.Surface.Center, f.Surface.Axis.normalize(), f.Area) for f in sh.Faces
            if type(f.Surface).__name__ == "Cylinder" and abs(f.Surface.Radius - radius) < tol]


def line_plane(p, d, q, n):
    return p + d * ((q - p).dot(n) / d.dot(n))


balls = [gshape(o).Solids[0] for o in parts("8mm Ball")]
ball_centres = [b.CenterOfMass for b in balls]
legs = []
for crank_obj in parts("Leg ASSY_Component8"):
    crank = gshape(crank_obj)
    hub = max(cylinders(crank, 10.75), key=lambda c: c[2])
    axis = hub[1]
    B = min(ball_centres, key=lambda c: (c - hub[0]).Length)
    A = line_plane(hub[0], axis, B, axis)                # pivot, projected into the leg plane
    P = min((line_plane(c[0], c[1], B, axis) for c in cylinders(crank, 2.0)), key=lambda p: p.z)
    radial = App.Vector(A.x, A.y, 0).normalize()
    solid = crank.Solids[0]
    G = solid.CenterOfMass
    # inertia of the crank about its pivot axis (unit density, mm^5)
    I_axis = solid.MatrixOfInertia
    Iax = sum(axis[i] * axis[j] * I_axis.A[4 * i + j] for i in range(3) for j in range(3))
    dG = (G - A) - axis * (G - A).dot(axis)
    Iax_pivot = Iax + solid.Volume * dG.Length ** 2
    legs.append(dict(
        az=math.degrees(math.atan2(B.y, B.x)),
        pivot_u=(A - App.Vector(0, 0, A.z)).Length, pivot_z=A.z,
        crank=(P - A).Length, crank_home=math.degrees(math.atan2((P - A).z, (P - A).dot(radial))),
        rod=(B - P).Length, joint_r=math.hypot(B.x, B.y), joint_z=B.z,
        crank_vol=solid.Volume, crank_com_u=(G - A).dot(radial), crank_com_v=(G - A).z,
        crank_I_pivot=Iax_pivot, leg_plane_offset=(App.Vector(0, 0, 0) - B).dot(axis),
    ))

plate = gshape(parts("Top ASSY_Component5")[0])
top_z = max(f.CenterOfMass.z for f in plate.Faces
            if type(f.Surface).__name__ == "Plane" and abs(f.normalAt(0, 0).z) > 0.999 and f.Area > 1e4)
bottom_z = min(f.CenterOfMass.z for f in plate.Faces
               if type(f.Surface).__name__ == "Plane" and abs(f.normalAt(0, 0).z) > 0.999 and f.Area > 1e4)
plate_r = max(c[0].Length * 0 + f.Surface.Radius for f in plate.Faces
              if type(f.Surface).__name__ == "Cylinder" for c in [(f.Surface.Center,)])
ps = plate.Solids[0]
pI = ps.MatrixOfInertia
rod = gshape(parts("Leg ASSY_Component9")[0]).Solids[0]
ball = gshape(parts("20mmBall")[0]).Solids[0]
ball_r = [f.Surface.Radius for f in ball.Faces if type(f.Surface).__name__ == "Sphere"][0]
lens = gshape(parts("OV2710_Component1")[-1])
cam_body = gshape(parts("OV2710_Component1")[0])


def mean(key):
    return sum(l[key] for l in legs) / len(legs)


def spread(key):
    return max(l[key] for l in legs) - min(l[key] for l in legs)


azs = sorted(l["az"] for l in legs)
lines = [
    "// GENERATED by tools/cad/extract_geometry.py from CAD/FullASSY.step. Do not edit by hand.",
    "// All lengths in millimetres, angles in degrees, in the CAD frame (z up, origin at the",
    "// centre of the plate's bottom face in the CAD pose). Values are the mean over the three",
    "// legs; the max-min spread across legs is noted where it is non-zero.",
    "#pragma once",
    "",
    "namespace bbp::cad {",
    "",
    "// Azimuths of the three spherical joints (sorted).",
    "inline constexpr double kLegAzimuthDeg[3] = {%.6f, %.6f, %.6f};" % tuple(azs),
    "inline constexpr double kPivotRadius = %.6f;   // spread %.2e" % (mean("pivot_u"), spread("pivot_u")),
    "inline constexpr double kPivotZ = %.6f;" % mean("pivot_z"),
    "inline constexpr double kCrankLength = %.6f;   // spread %.2e" % (mean("crank"), spread("crank")),
    "inline constexpr double kCrankAngleInCadDeg = %.6f;  // crank angle above horizontal in the CAD pose"
    % mean("crank_home"),
    "inline constexpr double kRodLength = %.6f;     // spread %.2e" % (mean("rod"), spread("rod")),
    "inline constexpr double kJointRadius = %.6f;" % mean("joint_r"),
    "inline constexpr double kJointZ = %.6f;" % mean("joint_z"),
    "// Perpendicular distance of each leg plane from the central axis (ideal design: 0).",
    "inline constexpr double kLegPlaneOffset = %.6f;" % mean("leg_plane_offset"),
    "",
    "inline constexpr double kPlateTopZ = %.6f;" % top_z,
    "inline constexpr double kPlateBottomZ = %.6f;" % bottom_z,
    "inline constexpr double kPlateRadius = %.6f;" % plate_r,
    "inline constexpr double kPlateVolume = %.6f;     // mm^3" % ps.Volume,
    "inline constexpr double kPlateComZ = %.6f;" % ps.CenterOfMass.z,
    "// Plate second moments about its centre of mass per unit density (mm^5).",
    "inline constexpr double kPlateIxxPerDensity = %.6e;" % pI.A11,
    "inline constexpr double kPlateIyyPerDensity = %.6e;" % pI.A22,
    "inline constexpr double kPlateIzzPerDensity = %.6e;" % pI.A33,
    "",
    "inline constexpr double kCrankVolume = %.6f;     // mm^3" % mean("crank_vol"),
    "// Crank centre of mass relative to the pivot in the CAD pose (radial u, vertical v).",
    "inline constexpr double kCrankComU = %.6f;" % mean("crank_com_u"),
    "inline constexpr double kCrankComV = %.6f;" % mean("crank_com_v"),
    "inline constexpr double kCrankIPivotPerDensity = %.6e;  // mm^5, about the pivot axis" % mean("crank_I_pivot"),
    "inline constexpr double kRodVolume = %.6f;       // mm^3" % rod.Volume,
    "",
    "inline constexpr double kBallRadius = %.6f;" % ball_r,
    "inline constexpr double kBallCentreZ = %.6f;" % ball.CenterOfMass.z,
    "",
    "// Camera (OV2710 module): top of the lens element and the module body extent.",
    "inline constexpr double kCameraLensTopZ = %.6f;" % lens.BoundBox.ZMax,
    "inline constexpr double kCameraLensBottomZ = %.6f;" % lens.BoundBox.ZMin,
    "inline constexpr double kCameraBodyBottomZ = %.6f;" % cam_body.BoundBox.ZMin,
    "inline constexpr double kCameraX = %.6f;" % lens.BoundBox.Center.x,
    "inline constexpr double kCameraY = %.6f;" % lens.BoundBox.Center.y,
    "",
    "}  // namespace bbp::cad",
    "",
]
with open(OUT, "w", newline="\n") as f:
    f.write("\n".join(lines))
print("wrote", OUT)
